(cl:defpackage action_test-msg
  (:use )
  (:export
   "<MESSAGEACTIONFEEDBACK>"
   "MESSAGEACTIONFEEDBACK"
   "<MESSAGEACTIONGOAL>"
   "MESSAGEACTIONGOAL"
   "<MESSAGEACTION>"
   "MESSAGEACTION"
   "<MESSAGEGOAL>"
   "MESSAGEGOAL"
   "<MESSAGERESULT>"
   "MESSAGERESULT"
   "<MESSAGEFEEDBACK>"
   "MESSAGEFEEDBACK"
   "<MESSAGEACTIONRESULT>"
   "MESSAGEACTIONRESULT"
  ))

