; Auto-generated. Do not edit!


(cl:in-package action_test-msg)


;//! \htmlinclude MessageGoal.msg.html

(cl:defclass <MessageGoal> (roslisp-msg-protocol:ros-message)
  ((number
    :reader number
    :initarg :number
    :type cl:float
    :initform 0.0))
)

(cl:defclass MessageGoal (<MessageGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MessageGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MessageGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_test-msg:<MessageGoal> is deprecated: use action_test-msg:MessageGoal instead.")))

(cl:ensure-generic-function 'number-val :lambda-list '(m))
(cl:defmethod number-val ((m <MessageGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_test-msg:number-val is deprecated.  Use action_test-msg:number instead.")
  (number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MessageGoal>) ostream)
  "Serializes a message object of type '<MessageGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'number))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MessageGoal>) istream)
  "Deserializes a message object of type '<MessageGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'number) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MessageGoal>)))
  "Returns string type for a message object of type '<MessageGoal>"
  "action_test/MessageGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MessageGoal)))
  "Returns string type for a message object of type 'MessageGoal"
  "action_test/MessageGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MessageGoal>)))
  "Returns md5sum for a message object of type '<MessageGoal>"
  "4dcebbc33e65171f948c63edad2d5dae")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MessageGoal)))
  "Returns md5sum for a message object of type 'MessageGoal"
  "4dcebbc33e65171f948c63edad2d5dae")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MessageGoal>)))
  "Returns full string definition for message of type '<MessageGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Washes your laundry~%#~%# goal message = the request~%float64 number		# the number of items to wash~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MessageGoal)))
  "Returns full string definition for message of type 'MessageGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Washes your laundry~%#~%# goal message = the request~%float64 number		# the number of items to wash~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MessageGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MessageGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MessageGoal
    (cl:cons ':number (number msg))
))
