; Auto-generated. Do not edit!


(cl:in-package action_test-msg)


;//! \htmlinclude MessageFeedback.msg.html

(cl:defclass <MessageFeedback> (roslisp-msg-protocol:ros-message)
  ((percentageDone
    :reader percentageDone
    :initarg :percentageDone
    :type cl:float
    :initform 0.0))
)

(cl:defclass MessageFeedback (<MessageFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MessageFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MessageFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_test-msg:<MessageFeedback> is deprecated: use action_test-msg:MessageFeedback instead.")))

(cl:ensure-generic-function 'percentageDone-val :lambda-list '(m))
(cl:defmethod percentageDone-val ((m <MessageFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_test-msg:percentageDone-val is deprecated.  Use action_test-msg:percentageDone instead.")
  (percentageDone m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MessageFeedback>) ostream)
  "Serializes a message object of type '<MessageFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percentageDone))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MessageFeedback>) istream)
  "Deserializes a message object of type '<MessageFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentageDone) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MessageFeedback>)))
  "Returns string type for a message object of type '<MessageFeedback>"
  "action_test/MessageFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MessageFeedback)))
  "Returns string type for a message object of type 'MessageFeedback"
  "action_test/MessageFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MessageFeedback>)))
  "Returns md5sum for a message object of type '<MessageFeedback>"
  "c53cad2b685a83c438629cd69eda4ba2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MessageFeedback)))
  "Returns md5sum for a message object of type 'MessageFeedback"
  "c53cad2b685a83c438629cd69eda4ba2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MessageFeedback>)))
  "Returns full string definition for message of type '<MessageFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%# here you might define some intermediate feedback message that reports about the current status of computation -> useful if the handling of the request might take several seconds or longer~%float32 percentageDone	# this is just a number telling how far the action accomplished the task (in the program the computations are delayed to show the effect)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MessageFeedback)))
  "Returns full string definition for message of type 'MessageFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%# here you might define some intermediate feedback message that reports about the current status of computation -> useful if the handling of the request might take several seconds or longer~%float32 percentageDone	# this is just a number telling how far the action accomplished the task (in the program the computations are delayed to show the effect)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MessageFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MessageFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MessageFeedback
    (cl:cons ':percentageDone (percentageDone msg))
))
