/* Auto-generated by genmsg_cpp for file /home/rmb-rj/git/ros-test/action_test/msg/MessageGoal.msg */
#ifndef ACTION_TEST_MESSAGE_MESSAGEGOAL_H
#define ACTION_TEST_MESSAGE_MESSAGEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace action_test
{
template <class ContainerAllocator>
struct MessageGoal_ {
  typedef MessageGoal_<ContainerAllocator> Type;

  MessageGoal_()
  : number(0.0)
  {
  }

  MessageGoal_(const ContainerAllocator& _alloc)
  : number(0.0)
  {
  }

  typedef double _number_type;
  double number;


  typedef boost::shared_ptr< ::action_test::MessageGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_test::MessageGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MessageGoal
typedef  ::action_test::MessageGoal_<std::allocator<void> > MessageGoal;

typedef boost::shared_ptr< ::action_test::MessageGoal> MessageGoalPtr;
typedef boost::shared_ptr< ::action_test::MessageGoal const> MessageGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::action_test::MessageGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::action_test::MessageGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace action_test

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::action_test::MessageGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::action_test::MessageGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::action_test::MessageGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4dcebbc33e65171f948c63edad2d5dae";
  }

  static const char* value(const  ::action_test::MessageGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4dcebbc33e65171fULL;
  static const uint64_t static_value2 = 0x948c63edad2d5daeULL;
};

template<class ContainerAllocator>
struct DataType< ::action_test::MessageGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_test/MessageGoal";
  }

  static const char* value(const  ::action_test::MessageGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::action_test::MessageGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Washes your laundry\n\
#\n\
# goal message = the request\n\
float64 number		# the number of items to wash\n\
\n\
";
  }

  static const char* value(const  ::action_test::MessageGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::action_test::MessageGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::action_test::MessageGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.number);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MessageGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_test::MessageGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::action_test::MessageGoal_<ContainerAllocator> & v) 
  {
    s << indent << "number: ";
    Printer<double>::stream(s, indent + "  ", v.number);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACTION_TEST_MESSAGE_MESSAGEGOAL_H

